# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_readings_dustbin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readings',
            name='dustbin_id',
        ),
    ]
