# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_readings_dustbin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='readings',
            name='dustbin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Dustbins'),
        ),
    ]
