# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_readings_dustbin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='readings',
            name='dustbin_id',
            field=models.IntegerField(default=0),
        ),
    ]
